name: create-release-upload

on: 
  push:
    tags:
    - 'v*'

env:
  XCODE_VERSION: 10.3

jobs:
  create_releases:
    name: create-releases
    runs-on: ubuntu-18.04
    outputs:
      release_url: ${{ steps.output_url.outputs.upload_url }}

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash
    - name: check package.json version
      env:
        version: ${{ steps.get_version.outputs.VERSION }}
      run: node ./tools/checker.js version ${version}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: true
      continue-on-error: true
    - name: Get release
      if: steps.create_release.outcome == 'failure'
      id: get_release
      uses: bruceadams/get-release@v1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: output url
      id: output_url
      run: |
        echo "::set-output name=upload_url::${{steps.get_release.outputs.upload_url}}${{steps.create_release.outputs.upload_url}}"

  upload-object-ubuntu:
    name: upload-object-ubuntu
    needs: create_releases
    runs-on: ubuntu-18.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.2
      timeout-minutes: 1
      with:
        node-version: 14
    - name: cmake version
      id: cmake_version
      run: |
        cmake --version
        cmake_version=$(cmake --version | head -n 1)
        echo ::set-output name=CMAKE_VERSION::${cmake_version}
    - name: update cmake
      if: "contains(${{steps.cmake_version.outputs.CMAKE_VERSION}}, '3.23.0')"
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.23.x'
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: list
      run: ls -a $GITHUB_WORKSPACE
    - name: create folder
      run: |
        echo "---- dump output data ----"
        mkdir dist
    - name: cmake-build
      id: cmake_build
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_SHARED=on -DENABLE_CAPI=off -DENABLE_TESTS=off -DTARGET_RPATH="@executable_path;/usr/local/lib;/usr/local/lib64;/usr/local/lib/x86_64-linux-gnu;./node_modules/cfd-js/build/Release;../node_modules/cfd-js/build/Release;../../node_modules/cfd-js/build/Release;../../../node_modules/cfd-js/build/Release;../../../../node_modules/cfd-js/build/Release;../../../../../node_modules/cfd-js/build/Release;../../../../../../node_modules/cfd-js/build/Release;./build/Release;./build/Release;./wrap_js/dl_lib/lib;./wrap_js/dl_lib/lib/x86_64-linux-gnu"
        cmake --build build --parallel 4 --config Release
        cd ../..
      timeout-minutes: 20
    - name: cmake-install
      run: |
        cd build
        sudo make install DESTDIR=../dist
        cd ..
        sudo rm -rf dist/usr/local/cmake/wallycore-* dist/usr/local/lib/pkgconfig/wallycore.pc
        sudo rm -rf dist/usr/local/lib/wallycore.*   dist/usr/local/lib/libwallycore.*
    - name: create archive file
      run: |
        cd dist
        zip -r cfd.zip usr
        echo "---- dump zip file ----"
        ls -l
    - name: output url
      id: get_url
      run: echo "::set-output name=upload_url::${{ needs.create_releases.outputs.release_url }}"
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_url.outputs.upload_url }}
        asset_path: ./dist/cfd.zip
        asset_name: cfdjs-api-${{ steps.get_version.outputs.VERSION }}-ubuntu1804-gcc-x86_64.zip
        asset_content_type: application/zip
    - name: waiting 30 sec
      run: sleep 30
    - name: npm install
      run: npm install
      timeout-minutes: 20
    - name: prebuild
      run: npm run prebuild_napi
    - name: prebuild upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run prebuild_upload_all -- ${GITHUB_TOKEN}
